[workspace]
resolver = "2"

members = [ "seqlock", "seqlock_macros","btree", "dev_utils", "umolc"]

[profile.test]

[profile.test-optimized]
inherits = "test"
opt-level = 3

[profile.bench]
debug = true
