[package]
name = "seqlock_macros"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = { version = "2.0.59",features = ["full"] }
proc-macro2 = "1.0.81"
quote = "1.0.36"
proc-macro-crate = "3.1.0"
itertools = "0.12.1"

[lib]
proc-macro =true