[package]
name = "btree"
version = "0.1.0"
edition = "2021"

[dependencies]
seqlock = {path = "../seqlock" }
indxvec = "1.9"
bytemuck = { version = "1.15.0",features = ["derive"] }
rand = { version = "0.8.5",features = ["small_rng"] }
bstr = "1.9.1"