[package]
name = "seqlock"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["asm_read"]
atomic_byte=[]
asm_read=[]

[dependencies]
as_base = "0.1.3"
bytemuck = "1.15.0"